"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { useEffect } from "react";
import ProfileHeader from "./components/header/ProfileHeader"
import Sidebar from "./components/sidebar/Sidebar";
import AboutUser from "./components/sections/aboutUser/AboutUser"
import Post from "./components/sections/posts/Posts"
import WorkExperience from "./components/sections/workExperience/WorkExperience"
import Education from "./components/sections/education/Education"
import AwardsAndCertifications from "./components/sections/awardsAndCertifications/AwardsAndCertifications"
import FeaturedVideos from "./components/sections/featuredVideos/FeaturedVideos"
import Calendar from "./components/calender/Calendar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function SpeakerUserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Ensure page always starts from the top
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <ProfileHeader />
      <div className="flex flex-col lg:flex-row items-stretch justify-between min-h-screen">
        <Sidebar />
        <div className="w-full bg-[#fffbf5]">
          <main className="flex flex-col items-center justify-between gap-5 py-5 px-4 lg:px-0">
            <AboutUser />
            <Calendar />
            <Post />
            <WorkExperience />
            <Education />
            <AwardsAndCertifications />
            <FeaturedVideos />
          </main>
        </div>
      </div>
      {children}
    </div>
  );
}